### ISSUE TITLE
Improve Messaging Around Failure to Convert Datatypes

### ISSUE THREAD

**Issue by jonwiggins** [Snowflake-Labs/mlflow-snowflake#17]
Hello,

While testing out this package I noticed I was getting the following error.

```python
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/snowflake/ml/mlflow/deploy/deployment_client.py", line 94, in create_deployment
    upload_model_from_mlflow(self._session, model_dir_path=model_path, udf_name=normalized_name, **parsed_config)
  File "/root/miniconda3/lib/python3.8/site-packages/snowflake/ml/mlflow/deploy/udf_util.py", line 392, in upload_model_from_mlflow
    _udf_helper_factory(
  File "/root/miniconda3/lib/python3.8/site-packages/snowflake/ml/mlflow/deploy/udf_util.py", line 220, in generate_udf
    self._autogen_model_infer_udf(
  File "/root/miniconda3/lib/python3.8/site-packages/snowflake/ml/mlflow/deploy/udf_util.py", line 135, in _autogen_model_infer_udf
    snowpark_input_types = [_DTYPE_TYPE_MAPPING[dt] for dt in input_types]
  File "/root/miniconda3/lib/python3.8/site-packages/snowflake/ml/mlflow/deploy/udf_util.py", line 135, in <listcomp>
    snowpark_input_types = [_DTYPE_TYPE_MAPPING[dt] for dt in input_types]
KeyError: dtype('O')
```
This was caused by mlflow inferring the model's signature input datatype as `Tensor (dtype: object, shape: [-1])`, from a numpy array of type object.
In my case it was solved after some debugging by calling `.astype(str)` on my numpy array prior to fitting the model.

It might be nice for future users if there was a more useful exception message.

Thanks,
Jon

**Comment by jonwiggins** [comment]
Also might be worth considering changing the API to allow people to pass in their expected snowflake in/out types directly, regardless of what mlflow inferred the signature as.

**Comment by sfc-gh-halu** [comment]
@jonwiggins , I created https://github.com/Snowflake-Labs/mlflow-snowflake/issues/23 to capture the requirement of explicit snowflake in/out types. Will close out this issue as enhanced error message change is merged into latest release.
